###
POST http://localhost:8080/api/admin/create
Content-Type: application/json

{
  "firstName": "Abebe5427",
  "lastName": "Kebede5427",
  "email": "abebe547@gmail.com",
  "phoneNumber": "091111117421",
  "password": "09111111177421"
}

###
GET http://localhost:8080/api/admin/list

###
PUT http://localhost:8080/api/admin/1
Content-Type: application/json

{
  "firstName": "Abeba",
  "lastName": "Kebede",
  "email": "abebe@gmail.com",
  "phoneNumber": "0911111111",
  "Passworde": "123@act"
}


###
DELETE http://localhost:8080/api/admin/1

###
POST http://localhost:8080/api/passenger/create
Content-Type: application/json

{
  "firstName": "Hana",
  "address": "AddisAbaba",
  "lastName": "Hailu",
  "email": "hana@gmail.com",
  "phoneNumber": "0922222222",
  "password": "456@act",
  "CreditCardNo": "12345"
}

###
GET http://localhost:8080/api/passenger/list

###
PUT http://localhost:8080/api/passenger/1
Content-Type: application/json

{
  "firstName": "Hannan",
  "address": "Addis Ababa",
  "lastName": "Sisay",
  "email": "hannan@gmail.com",
  "phoneNumber": "0922222222",
  "Passworde": "456@act",
  "CreditCardNo": 12345
}

###
DELETE http://localhost:8080/api/passenger/1

###
POST http://localhost:8080/api/reservation/create
Content-Type: application/json

{
  "ScheduleId": 1,
  "CustomerId": 1,
  "SeatNo": 100
}

###
GET http://localhost:8080/api/reservation/list

###
PUT http://localhost:8080/api/reservation/1
Content-Type: application/json

{
  "ScheduleId": 1,
  "CustomerId": 1,
  "SeatNo": 101
}

###
DELETE http://localhost:8080/api/reservation/1

###
POST http://localhost:8080/api/schedule/create
Content-Type: application/json

{
  "Airline": "Ethiopian",
  "FlightName": "LFAB",
  "FlightNum": "LFAB100",
  "Origin": "Addis Ababa",
  "OriginLat": "33",
  "OriginLong": "44",
  "Destination": "Hawasa",
  "DestinationLat": "22",
  "DestinationLong": "44",
  "DepartureTime": "12:00GMT",
  "ArrivalTime": "13:GMT",
  "Duration": "50min",
  "SeatClass": "Economy",
  "Status": "Active",
  "AvailableSeats": 100,
  "NumofSeats": 100,
  "Price": 2500.00
}

###
GET http://localhost:8080/api/schedule/list

###
PUT http://localhost:8080/api/schedule/1
Content-Type: application/json

{
  "Price": 3500.00
}

###
DELETE http://localhost:8080/api/schedule/1

